apiVersion: v1
kind: Service
metadata:
  name: db  # To będzie nazwa DNS, pod którą Ghost połączy się z MySQL
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP  # Używamy ClusterIP, ponieważ dostęp potrzebny jest tylko wewnątrz klastra

