apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 2368
      targetPort: 2368
      nodePort: 32127
  type: LoadBalancer  # Możesz użyć NodePort, jeśli LoadBalancer nie jest dostępny

