apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        ports:
        - containerPort: 2368
        env:
        - name: database__client
          value: "mysql"
        - name: database__connection__host
          value: "db"
        - name: database__connection__user
          value: "root"
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: database__connection__database
          value: "ghost"

